### ISSUE TITLE
Fix caching issue in Datafiles

### ISSUE THREAD

**Issue by SpaceKookie** [tr-lonelyrobot/reedb#10]
```
/home/spacekookie/Documents/code/projects/ruby/reedb/reedb/lib/reedb/datafile.rb:73:in `block in insert': undefined method `each' for "www.lonelyrobot.io":String (NoMethodError)
	from /home/spacekookie/Documents/code/projects/ruby/reedb/reedb/lib/reedb/datafile.rb:68:in `each'

Not incrementing version because write cycle too short.
```

Fix this issue where cache cycles will crash the daemon because of malformed data.

**Comment by SpaceKookie** [comment]
Was fixed in some commit a few days ago. Data now gets checked for integrity and reedb throws errors if data is malformed instead of crashing. ~CLOSE
