### ISSUE TITLE
reedb mit ruby 2.2.0 geht kaputt

### ISSUE THREAD

**Issue by XenGi** [tr-lonelyrobot/reedb#16]
```
/usr/lib/ruby/2.2.0/rubygems.rb:198:in `rescue in try_activate': undefined method `activate' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/2.2.0/rubygems.rb:195:in `try_activate'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /usr/lib/ruby/gems/2.2.0/gems/reedb-0.10.rc1/bin/reedbd:14:in `<top (required)>'
	from /usr/bin/reedbd:23:in `load'
	from /usr/bin/reedbd:23:in `<main>'
```

**Comment by SpaceKookie** [comment]
Reedb wird jetzt nicht mehr mit Ruby 2.2 laufen, heißt der "bug" ist eigentlich resolved. Aber ich werde trotzdem versuchen den daemon auf 2.2 zu migrieren (soon tm), weil mit dem schnellen release Zyklus von Ruby versionen EOL for 2.1 bestimmt auch bald vor der Tür steht ;)

**Comment by XenGi** [comment]
na dann sollte das hier erstmal "wontfix" sein.
