### ISSUE TITLE
Permission denied @ rb_sysopen - reedb-0.11/lib/reedb/reedb.pid (Errno::EACCES)

### ISSUE THREAD

**Issue by SpaceKookie** [tr-lonelyrobot/reedb#21]
```
[♀] ♥ reedbd run
/home/spacekookie/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/pidfile.rb:92:in `initialize': Permission denied @ rb_sysopen - /home/spacekookie/.rvm/gems/ruby-2.1.5/gems/reedb-0.11/lib/reedb/reedb.pid (Errno::EACCES)
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/pidfile.rb:92:in `open'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/pidfile.rb:92:in `pid='
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/application.rb:167:in `start_load'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/application.rb:297:in `start'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/controller.rb:59:in `run'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons.rb:144:in `block in run'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `call'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `catch_exceptions'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/gems/daemons-1.2.2/lib/daemons.rb:143:in `run'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/gems/reedb-0.11/bin/reedbd:103:in `<top (required)>'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/bin/reedbd:23:in `load'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/bin/reedbd:23:in `<main>'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /home/spacekookie/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by SpaceKookie** [comment]
This is a bug when installing Reedb via the system package manager (apt, dnf, etc) and also using rvm. Because the package manager will install things as root the gem directory in the user path will be owned by root. Thus making it impossible to create a .pid file there as a user.

Different approaches can be taken for packaging then.

1. Clauses could be added to the install spec to chown the install dir to the user if it is under /home. (hacky)
2. The spec could check for RVM and then switch to the system ruby (less hacky)
3. ??? I'm open to your suggestions. Preferably people with packaging experience.
